/**
 * Constants shared between backend + mobile. NEVER rename a value here;
 * only add new ones — clients and server must agree on the wire format.
 */

export const SharedHeaders = {
  REQUEST_ID: 'x-request-id',
  CORRELATION_ID: 'x-correlation-id',
  IDEMPOTENCY_KEY: 'idempotency-key',
  CLIENT_VERSION: 'x-client-version',
  CLIENT_PLATFORM: 'x-client-platform',
  DEVICE_ID: 'x-device-id',
} as const;

export const SharedErrorCodes = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_THROTTLED: 'OTP_THROTTLED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  PASSWORD_WEAK: 'PASSWORD_WEAK',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',

  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_LOCKED: 'WALLET_LOCKED',
  WALLET_FROZEN: 'WALLET_FROZEN',
  WALLET_CLOSED: 'WALLET_CLOSED',
  WALLET_AMOUNT_INVALID: 'WALLET_AMOUNT_INVALID',
  WALLET_CURRENCY_MISMATCH: 'WALLET_CURRENCY_MISMATCH',
  WALLET_LIMIT_EXCEEDED: 'WALLET_LIMIT_EXCEEDED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_ALREADY_REVERSED: 'TRANSACTION_ALREADY_REVERSED',
  TRANSACTION_NOT_REVERSIBLE: 'TRANSACTION_NOT_REVERSIBLE',
  LEDGER_IMBALANCE: 'LEDGER_IMBALANCE',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
  CONTEST_FULL: 'CONTEST_FULL',
  CONTEST_CLOSED: 'CONTEST_CLOSED',
  CONTEST_ALREADY_JOINED: 'CONTEST_ALREADY_JOINED',
  TEAM_INVALID: 'TEAM_INVALID',
  KYC_REQUIRED: 'KYC_REQUIRED',

  // Sports / Matches (PHASE 4)
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  TOURNAMENT_NOT_FOUND: 'TOURNAMENT_NOT_FOUND',
  SPORT_NOT_SUPPORTED: 'SPORT_NOT_SUPPORTED',
  SYNC_PROVIDER_FAILED: 'SYNC_PROVIDER_FAILED',
  SYNC_ALREADY_IN_PROGRESS: 'SYNC_ALREADY_IN_PROGRESS',
  MATCH_NOT_LIVE: 'MATCH_NOT_LIVE',
  MATCH_LOCK_VIOLATED: 'MATCH_LOCK_VIOLATED',
} as const;

export type SharedErrorCode = (typeof SharedErrorCodes)[keyof typeof SharedErrorCodes];
